spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: shortify
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  docker:
    compose:
      lifecycle-management: start_only

shortify:
  word-list: static/word-list.txt

rate-limit:
  endpoints:
    [/api/v1/links/]:
      method: POST
      limit: 10
    [/api/v1/links/**]:
      method: GET
      limit: 30